// <auto-generated />
using System;
using GraphQLHotChocolate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLHotChocolate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1");

            modelBuilder.Entity("GraphQLHotChocolate.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SuperheroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0362889d-d800-474b-9b6d-a2f8e44e9cf7"),
                            Description = "Batman Begins is a 2005 superhero film directed by Christopher Nolan and written by Nolan and David S. Goyer. Based on the DC Comics character Batman, it stars Christian Bale as Bruce Wayne / Batman, with Michael Caine, Liam Neeson, Katie Holmes, Gary Oldman,",
                            Instructor = "Christopher Nolan",
                            ReleaseDate = new DateTime(2005, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Title = "Batman Begins"
                        },
                        new
                        {
                            Id = new Guid("dfb37a4f-5d14-4c90-8806-13315031925b"),
                            Description = "The Dark Knight is a 2008 superhero film directed, produced, and co-written by Christopher Nolan. Based on the DC Comics character Batman, the film is the second installment of Nolan's The Dark Knight Trilogy and a sequel to 2005's Batman Begins, starring Christian Bale and supported by Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal, and Morgan Freeman.",
                            Instructor = "Christopher Nolan",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = new Guid("1dc5c062-d7bf-44fe-b458-0c45c8fc06ad"),
                            Description = "The Dark Knight Rises is a 2012 superhero film directed by Christopher Nolan, who co-wrote the screenplay with his brother Jonathan Nolan, and the story with David S. Goyer.",
                            Instructor = "Christopher Nolan",
                            ReleaseDate = new DateTime(2012, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Title = "The Dark Knight Rises"
                        },
                        new
                        {
                            Id = new Guid("ce327da2-06bf-4921-9356-2ff92da6bec6"),
                            Description = "The Batman is a reboot of the Batman film franchise. The film was directed by Matt Reeves, who wrote the screenplay with Peter Craig.",
                            Instructor = "Matt Reeves",
                            ReleaseDate = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Title = "The Batman"
                        },
                        new
                        {
                            Id = new Guid("3729a154-03b4-48fe-971a-91b2b719a5ac"),
                            Description = "Star Wars (retroactively titled Star Wars: Episode IV – A New Hope) is a 1977 American epic space opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            Instructor = "George Lucas",
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("107aa9b9-b152-42d8-94b6-53ec14185598"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("9eba5008-29f4-4798-98d6-8ff527c1c252"),
                            Description = "The Empire Strikes Back (also known as Star Wars: Episode V – The Empire Strikes Back) is a 1980 American epic space opera film directed by Irvin Kershner and written by Leigh Brackett and Lawrence Kasdan, based on a story by George Lucas.",
                            Instructor = "Irvin Kershner",
                            ReleaseDate = new DateTime(1980, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("107aa9b9-b152-42d8-94b6-53ec14185598"),
                            Title = "Star Wars: Episode V – The Empire Strikes Back"
                        },
                        new
                        {
                            Id = new Guid("221f5718-f525-42a7-903a-8e40b7ae0df4"),
                            Description = "Return of the Jedi (also known as Star Wars: Episode VI – Return of the Jedi) is a 1983 American epic space opera film directed by Richard Marquand. The screenplay is by Lawrence Kasdan and George Lucas from a story by Lucas, who was also the executive producer.",
                            Instructor = "Richard Marquand",
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("107aa9b9-b152-42d8-94b6-53ec14185598"),
                            Title = "Star Wars: Episode VI – Return of the Jedi"
                        },
                        new
                        {
                            Id = new Guid("89f88e7f-2925-4cd5-9d30-49f6fb99c263"),
                            Description = "Spider-Man: Homecoming is a 2017 American superhero film based on the Marvel Comics character Spider-Man. It is the second reboot of the Spider-Man film franchise and the sixteenth film in the Marvel Cinematic Universe (MCU). The movie follows the story of Peter Parker as he navigates high school life and his newfound abilities as Spider-Man, while facing the villainous Vulture.",
                            Instructor = "Jon Watts",
                            ReleaseDate = new DateTime(2017, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Title = "Spider-Man: Homecoming"
                        },
                        new
                        {
                            Id = new Guid("c3b10d28-2335-4677-ba4e-4806b2186c4c"),
                            Description = "Spider-Man: Far From Home is a 2019 American superhero film based on the Marvel Comics character Spider-Man. It is the sequel to Spider-Man: Homecoming and the 23rd film in the Marvel Cinematic Universe (MCU). In the movie, Peter Parker embarks on a school trip to Europe but is recruited by Nick Fury to help fight against the Elementals, alongside the mysterious superhero Mysterio.",
                            Instructor = "Jon Watts",
                            ReleaseDate = new DateTime(2019, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Title = "Spider-Man: Far From Home"
                        },
                        new
                        {
                            Id = new Guid("bbc07d5f-d12b-4216-80cc-12f63bae5c4e"),
                            Description = "Spider-Man: No Way Home is an upcoming American superhero film based on the Marvel Comics character Spider-Man. It is the third film in the Spider-Man: Homecoming trilogy and the 27th film in the Marvel Cinematic Universe (MCU). The movie will continue the story of Peter Parker as he deals with the consequences of his secret identity being revealed and explores the multiverse with the help of Doctor Strange.",
                            Instructor = "Jon Watts",
                            ReleaseDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Title = "Spider-Man: No Way Home"
                        },
                        new
                        {
                            Id = new Guid("8091d052-0044-4748-958f-f2c0fc340880"),
                            Description = "The Amazing Spider-Man is a 2012 American superhero film based on the Marvel Comics character Spider-Man. It is the fourth theatrical Spider-Man film produced by Columbia Pictures and Marvel Entertainment, and a reboot of Sam Raimi's Spider-Man trilogy. The film tells the story of Peter Parker, a high school student who gains spider-like abilities and becomes the superhero Spider-Man.",
                            Instructor = "Marc Webb",
                            ReleaseDate = new DateTime(2012, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Title = "The Amazing Spider-Man"
                        },
                        new
                        {
                            Id = new Guid("b778f283-e5cc-42e6-af6a-aa2fd7763494"),
                            Description = "Spider-Man is a 2002 American superhero film directed by Sam Raimi. It is based on the Marvel Comics character Spider-Man and tells the origin story of Peter Parker, a high school student who develops spider-like abilities after being bitten by a genetically-engineered spider. The film follows Peter as he learns to use his powers and faces off against the Green Goblin, a villainous alter ego of Norman Osborn.",
                            Instructor = "Sam Raimi",
                            ReleaseDate = new DateTime(2002, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Title = "Spider-Man"
                        });
                });

            modelBuilder.Entity("GraphQLHotChocolate.Models.SuperHero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Superheroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Description = "Batman was originally introduced as a ruthless vigilante who frequently killed or maimed criminals, but evolved into a character with a stringent moral code and strong sense of justice. Unlike most superheroes, Batman does not possess any superpowers, instead relying on his intellect, fighting skills, and wealth.",
                            Height = 1.9299999999999999,
                            Name = "Batman"
                        },
                        new
                        {
                            Id = new Guid("107aa9b9-b152-42d8-94b6-53ec14185598"),
                            Description = "Luke Skywalker was a Tatooine farmboy who rose from humble beginnings to become one of the greatest Jedi the galaxy has ever known. Along with his friends Princess Leia and Han Solo, Luke battled the evil Empire, discovered the truth of his parentage, and ended the tyranny of the Sith.",
                            Height = 1.7,
                            Name = "Luke Skywalker"
                        },
                        new
                        {
                            Id = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Description = "Spider-Man, also known as Peter Parker, is a teenage superhero with the proportionate strength, speed, and agility of a spider. He can cling to walls and has a spider-sense that alerts him to danger. Spider-Man uses his powers to protect New York City from various supervillains.",
                            Height = 1.78,
                            Name = "Spider-Man"
                        });
                });

            modelBuilder.Entity("GraphQLHotChocolate.Models.SuperPower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SuperheroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Superpower")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.ToTable("Superpowers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16d0b40f-7fe4-4573-b572-f7dc02b42777"),
                            Description = "He's always a step ahead.",
                            SuperheroId = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Superpower = "Intellect."
                        },
                        new
                        {
                            Id = new Guid("39fa1b01-669a-4544-858d-eacd4d2c6a54"),
                            Description = "Sublime fighting skills.",
                            SuperheroId = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Superpower = "Fighting"
                        },
                        new
                        {
                            Id = new Guid("4b3ab9d0-607f-43c3-81db-045cc36a37b8"),
                            Description = "He got a lot of money",
                            SuperheroId = new Guid("c8d0cd36-3605-4454-b8c8-a5d7bced1d2a"),
                            Superpower = "Wealth."
                        },
                        new
                        {
                            Id = new Guid("78f2bbd0-4aa4-45cd-8711-5f3934501f0c"),
                            Description = "Luke Skywalker is able to deflect fire from a blaster back at the opponent firing. This enables Luke to turn someone else's weapon against them.",
                            SuperheroId = new Guid("107aa9b9-b152-42d8-94b6-53ec14185598"),
                            Superpower = "Deflect blaster power."
                        },
                        new
                        {
                            Id = new Guid("448723b4-dc81-412b-8c76-a41490df729c"),
                            Description = "Luke Skywalker has the ability to move objects with his mind. He can manipulate and control objects using telekinesis, allowing him to lift, push, or pull things without physical contact.",
                            SuperheroId = new Guid("107aa9b9-b152-42d8-94b6-53ec14185598"),
                            Superpower = "Telekinesis"
                        },
                        new
                        {
                            Id = new Guid("63cc33fc-7ba2-4ff6-be21-c36c3d2261a6"),
                            Description = "Luke Skywalker possesses the rare ability to project a realistic and powerful image of himself across vast distances. This power allows him to deceive and distract his enemies, giving him an advantage in battles and strategic situations.",
                            SuperheroId = new Guid("107aa9b9-b152-42d8-94b6-53ec14185598"),
                            Superpower = "Force Projection"
                        },
                        new
                        {
                            Id = new Guid("2ee5d9c3-8176-4f1d-ad32-8782ad954628"),
                            Description = "Spider-Man's spider-sense grants him an advanced warning system, allowing him to sense danger before it occurs, including incoming attacks, imminent threats, or hidden enemies.",
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Superpower = "Spider-Sense"
                        },
                        new
                        {
                            Id = new Guid("810ea0dd-052c-47b1-b291-a48229876744"),
                            Description = "Spider-Man possesses exceptional agility and reflexes, surpassing those of a regular human. He can perform acrobatic maneuvers, dodge attacks with ease, and move swiftly in various environments, making him incredibly difficult to hit or capture.",
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Superpower = "Increased Agility"
                        },
                        new
                        {
                            Id = new Guid("57dbab0e-5f00-4cfc-b712-f80252ba0b47"),
                            Description = "Spider-Man can generate and shoot strong, adhesive webs from devices he created called web-shooters. He uses these webs to swing through the city, create barriers, restrain enemies, or as a versatile tool in combat and rescue operations.",
                            SuperheroId = new Guid("c26365a9-f493-4041-a977-01c05041ea43"),
                            Superpower = "Web-Slinging"
                        });
                });

            modelBuilder.Entity("GraphQLHotChocolate.Models.Movie", b =>
                {
                    b.HasOne("GraphQLHotChocolate.Models.SuperHero", "Superhero")
                        .WithMany("Movies")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("GraphQLHotChocolate.Models.SuperPower", b =>
                {
                    b.HasOne("GraphQLHotChocolate.Models.SuperHero", "Superhero")
                        .WithMany("Powers")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("GraphQLHotChocolate.Models.SuperHero", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Powers");
                });
#pragma warning restore 612, 618
        }
    }
}
